# Site settings
title: Antão Almada's Blog
description: 'The official blog of Antão Almada. A blog about software development, technology and other stuff.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aalmada.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/aalmada-logo-full.svg"
logo-icon: "/assets/img/branding/aalmada-symbol.svg"
logo-icon-SEO: "/assets/img/branding/aalmada-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/aalmada-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Antão Almada # add your name
author-pic: antaoalmada_400x400.jpg
about-author: My tech journey, starting in the late '90s with virtual reality, spans full-body interaction and augmented reality. I began coding on a ZX Spectrum 48K and earned a Computer Science degree from the NOVA University Lisbon. While I spent many years using C++, C# is my primary coding tool today. Most of my open-source projects are within the NetFabric organization in GitHub. I also contributed to other projects including notable ones like ReactiveUI and MixedRealityToolkit-Unity. Beyond coding, I balance family life and enjoy dirt biking on pump tracks and exploring mountain bike trails in my free time.
# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website
linkedin: antaoalmada # Add your Linkedin handle
github: aalmada # Add your Github handle
twitter: # Add your Twitter handle
bandcamp: # Add your Bandcamp username
stackoverflow: 861773 # Add your stackoverflow account

# Newsletter
mailchimp:

# Tracker
analytics: G-W2YEK46D0J
fbadmin: 

# Paginate
paginate: 10
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: aalmada/aalmada.github.io # The GitHub repo URL.  https://utteranc.es/
  issue_term: title # The GitHub issue label
  label: Comment # The GitHub comments label
  theme: preferred-color-scheme # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: Europe/Lisbon # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]